[project]
name = "Spyrit"
description = "A user-friendly MUD/MUSH/MOO graphical client."
authors = [{ name = "P. Varet", email = "p.varet@gmail.com" }]
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: X11 Applications :: Qt",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Communications",
    "Topic :: Games/Entertainment :: Multi-User Dungeons (MUD)",
]
dynamic = ["version"]
requires-python = ">=3.13"

dependencies = ["PySide6>=6.9.1", "regex", "stackprinter", "SunsetSettings>=0.7.0"]

[project.gui-scripts]
spyrit = "spyrit.main:run"

[dependency-groups]
tests = [
    # Test-specific dependencies.
    "hypothesis",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "pytest-qt",
]
dev = [
    # Dev dependencies.
    { include-group = "tests" },
    "mypy",
    "ruff",
    "ty",
    "types-regex",
]

[build-system]
requires = [
    "hatchling",
    "hatch-build-scripts",
    "hatch-vcs",
    # Note that the following are needed at build time in order to compile resources.
    "pip",
    "PySide6",
]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"

[tool.hatch.build.targets.wheel]
# Explicitly add the built resources file to the wheel, even if the VCS configuration is
# set to ignore it.
artifacts = ["src/spyrit/__resources__.py"]

[[tool.hatch.build.targets.wheel.hooks.build-scripts.scripts]]
commands = ["""
    pyside6-rcc \
        --generator python \
        --compress 9 \
        --threshold 0.95 \
        --output src/spyrit/__resources__.py \
        resources/resources.qrc
"""]

[tool.pytest.ini_options]
addopts = [
    "-vv",
    # Recommended import mode.
    "--import-mode=importlib",
    # Coverage.
    "--cov",
    "--cov-branch",
    "--cov-report=term-missing",
]

[tool.ruff]
# Use the default line length.
line-length = 88

[tool.ruff.lint]
# Enable all linting rules by default.
select = ["ALL"]
ignore = [
    "ANN401",  # We're in fact careful about usage of Any.
    "COM812",  # Can confuse the Ruff formatter.
    "ISC001",  # Can confuse the Ruff formatter.
    "N815",    # Use Qt-style camel-case names for signals, for now.
    "FIX002",  # We do track the TODOs, actually.
    "LOG015",  # We use the root logger a lot, actually. TODO: Fix that.
    "N802",    # We in fact use camelCase method names.
    "PLW2901", # We manipulate iteration variables a lot actually.
    "TC006",   # Obsoleted by PEP 563 (future type annotations).
    "TD002",   # We only use simple TODOs.
    "TD003",   # We only use simple TODOs.
    "D",       # Ignore docstring style linting for now. Revisit later.
    "FBT",     # "Boolean trap" checks have a lot of false positives.
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "S101",    # Tests use assert.
    "PLR2004", # Magic values in comparisons occur a lot in tests.
    "SLF001",  # Tests may call private methods.
]
"demo_*.py" = [
    "T201", # Demos can use print().
]

[tool.coverage.run]
source_dirs = ["src/", "tests/"]
omit        = ["__resources__.py", "demo_*.py"]

# # Disable a spurious warning caused by coverage getting confused about temporary
# # shiboken-related files.
# disable_warnings = ["couldnt-parse"]

[tool.mypy]
packages               = ["spyrit"]
strict                 = true
follow_untyped_imports = true
exclude_gitignore      = true
pretty                 = true
