[build-system]
requires      = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Spyrit"
description = "A user-friendly MUD/MUSH/MOO graphical client."
authors = [{ name = "P. Varet", email = "p.varet@gmail.com" }]
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: X11 Applications :: Qt",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Communications",
    "Topic :: Games/Entertainment :: Multi-User Dungeons (MUD)",
]
dynamic = ["version"]
requires-python = ">=3.12"

dependencies = ["PySide6>=6.9.1", "regex", "stackprinter", "SunsetSettings>=0.7.0"]

[project.optional-dependencies]
tests = ["hypothesis", "pytest", "pytest-cov", "pytest-mock"]
dev   = ["pyright", "types-regex"]

[project.gui-scripts]
spyrit = "spyrit.main:run"

[tool.pytest.ini_options]
addopts = "-vv"

[tool.ruff]
# Use the default line length.
line-length    = 88
extend-exclude = ["spyrit/resources/___compiled.py"]

[tool.ruff.lint]
# Enable all linting rules by default.
select = ["ALL"]
ignore = [
    "ANN401",  # We're in fact careful about usage of Any.
    "COM812",  # Can confuse the Ruff formatter.
    "ISC001",  # Can confuse the Ruff formatter.
    "FIX002",  # We do track the TODOs, actually.
    "LOG015",  # We use the root logged a lot, actually. TODO: Fix that.
    "N802",    # We in fact use camelCase method names.
    "PLW2901", # We manipulate iteration variables a lot actually.
    "TC006",   # Obsoleted by PEP 563 (future type annotations).
    "TD002",   # We only use simple TODOs.
    "TD003",   # We only use simple TODOs.
    "D",       # Ignore docstring style linting for now. Revisit later.
    "FBT",     # "Boolean trap" checks have a lot of false positives.
]
exclude = ["testing/*"]

[tool.hatch.version]
path    = "spyrit/constants.py"
pattern = 'SPYRIT_VERSION *:? *\w* *= *"(?P<version>[\w.-]+)"'

[tool.hatch.build.targets.wheel]
packages = ["spyrit/"]

[tool.hatch.envs.hatch-test]
# This forces hatch test to use the pytest ini options listed above.
default-args = []

# This makes this environment use the "tests" optional dependencies above. Hatch
# installs its own set by default, but explicit is better than implicit.
features = ["tests"]

# Parallelizes test execution.
parallel = true

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.12", "3.13"]

[tool.hatch.envs.dev]
# This is the environment used for developping the app.
features = ["dev", "tests"]

[tool.hatch.envs.hatch-static-analysis]
# Require a version of Ruff that agrees with the linting parameters above.
dependencies = ["ruff>=0.12.1"]

# Disable Hatch's custom Ruff defaults so that our linting parameters above are the
# entirety of what is used.
config-path = "none"
